title: Student Portfolio
description: Portfolio site
url: "https://estillcountyatc-computerscience.github.io"    # your actual user URL
baseurl: "/portfolio-template"                          # empty for user sites

# Theme choice (use one)
theme: jekyll-theme-cayman
# OR:
# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
#   - jekyll-remote-theme

# Optional but helpful to silence metadata warnings:
repository: EstillCountyATC-ComputerScience/portfolio-template
